//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MahadevEnterprise.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceMaster
    {
        public int InvoiceId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<decimal> GST { get; set; }
        public Nullable<decimal> CGST { get; set; }
        public Nullable<decimal> TAX { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
    }
}
